name       : haskell-heaps
version    : 0.3.6
release    : 2
source     :
    - https://hackage.haskell.org/package/heaps-0.3.6/heaps-0.3.6.tar.gz : 181c3cd7f2be698f903dc9649e5ec9311245ad2b9fed91b61f05d0dd7b7dddb2
license    : BSD-3-Clause
component  : programming.haskell
summary    : Asymptotically optimal Brodal/Okasaki bootstrapped skew-binomial heaps from the paper "Optimal Purely Functional Priority Queues", extended with a Foldable interface.
description: |
    Asymptotically optimal Brodal/Okasaki bootstrapped skew-binomial heaps from the paper "Optimal Purely Functional Priority Queues", extended with a Foldable interface.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
