name       : haskell-heaps
version    : 0.3.3
release    : 1
source     :
    - http://hackage.haskell.org/package/heaps-0.3.3/heaps-0.3.3.tar.gz : 04e358d3e6d8ca7786749b6d3945e18159506f8b21ca48b1913c771dcaae1537
license    : BSD-3-Clause
component  : programming.haskell
summary    : Asymptotically optimal Brodal/Okasaki bootstrapped skew-binomial heaps from the paper "Optimal Purely Functional Priority Queues", extended with a Foldable interface.
description: |
    Asymptotically optimal Brodal/Okasaki bootstrapped skew-binomial heaps from the paper "Optimal Purely Functional Priority Queues", extended with a Foldable interface.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
