name       : haskell-heaps
version    : 0.3.6.1
release    : 3
source     :
    - https://hackage.haskell.org/package/heaps-0.3.6.1/heaps-0.3.6.1.tar.gz : 91d552f3c8992f745607de39239b950db78295b533eda43d083699872a4ee36d
license    : BSD-3-Clause
component  : programming.haskell
summary    : Asymptotically optimal Brodal/Okasaki bootstrapped skew-binomial heaps from the paper "Optimal Purely Functional Priority Queues", extended with a Foldable interface.
description: |
    Asymptotically optimal Brodal/Okasaki bootstrapped skew-binomial heaps from the paper "Optimal Purely Functional Priority Queues", extended with a Foldable interface.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
